;
; File generated by cc65 v 2.19 - Git ce3bcad
;
	.fopt		compiler,"cc65 v 2.19 - Git ce3bcad"
	.setcpu		"6502"
	.smart		on
	.autoimport	on
	.case		on
	.debuginfo	off
	.importzp	sp, sreg, regsave, regbank
	.importzp	tmp1, tmp2, tmp3, tmp4, ptr1, ptr2, ptr3, ptr4
	.macpack	longbranch
	.export		_main

; ---------------------------------------------------------------
; int __near__ main (void)
; ---------------------------------------------------------------

.segment	"CODE"

.proc	_main: near

.segment	"CODE"

	lda     #$00
	sta     $0040
L0024:	lda     $0040
	cmp     #$FF
	bcs     L0025
	ldy     $0040
	lda     $EFF0,y
	sta     M0002
	lda     #$20
	sta     $2006
	lda     $0040
	sta     $2006
	lda     M0002
	sta     $2007
	inc     $0040
	jmp     L0024
L0025:	lda     #$00
	sta     $0040
L0026:	lda     $0040
	cmp     #$FF
	bcs     L0027
	ldy     $0040
	lda     $F0F0,y
	sta     M0002
	lda     #$21
	sta     $2006
	lda     $0040
	sta     $2006
	lda     M0002
	sta     $2007
	inc     $0040
	jmp     L0026
L0027:	lda     #$00
	sta     $0040
L0028:	lda     $0040
	cmp     #$FF
	bcs     L0029
	ldy     $0040
	lda     $F1F0,y
	sta     M0002
	lda     #$22
	sta     $2006
	lda     $0040
	sta     $2006
	lda     M0002
	sta     $2007
	inc     $0040
	jmp     L0028
L0029:	lda     #$00
	sta     $0040
L002A:	lda     $0040
	cmp     #$C0
	bcs     L002B
	ldy     $0040
	lda     $F2F0,y
	sta     M0002
	lda     #$23
	sta     $2006
	lda     $0040
	sta     $2006
	lda     M0002
	sta     $2007
	inc     $0040
	jmp     L002A
L002B:	lda     #$BF
	sta     $0040
L002C:	lda     $0040
	cmp     #$20
	beq     L002E
	ldy     $0040
	lda     $FC00,y
	sta     M0002
	lda     #$3F
	sta     $2006
	lda     $0040
	sta     $2006
	lda     M0002
	sta     $2007
	inc     $0040
	jmp     L002C
L002E:	sta     $2006
	lda     #$00
	sta     $2006
	sta     $2007
	lda     #$1E
	sta     $2001
L002F:	lda     #$01
	sta     $4016
	lda     #$00
	sta     $4016
	sta     M0001
L0030:	lda     M0001
	cmp     #$08
	beq     L0031
	lda     $4016
	and     #$01
	sta     $0030
	lda     $0031
	asl     a
	sta     $0031
	lda     $0030
	ora     $0031
	sta     $0031
	inc     M0001
	jmp     L0030
L0031:	lda     $0031
	and     #$0F
	sta     $0032
	lda     $0031
	asl     a
	asl     a
	asl     a
	asl     a
	and     #$0F
	sta     $0033
	lda     $0034
	cmp     $0032
	beq     L0032
	lda     #$00
	sta     $2001
	lda     #$20
	sta     $2006
	sta     $2006
	lda     $0032
	sta     $2007
	lda     #$1E
	sta     $2001
	lda     $0032
	sta     $0034
L0032:	lda     $0035
	cmp     $0033
	beq     L002F
	lda     #$00
	sta     $2001
	lda     #$20
	sta     $2006
	lda     #$21
	sta     $2006
	lda     $0033
	sta     $2007
	lda     #$1E
	sta     $2001
	lda     $0033
	sta     $0035
	jmp     L002F

.segment	"BSS"

M0001:
	.res	6,$00
M0002:
	.res	1,$00

.endproc

