;
; File generated by cc65 v 2.19 - Git ce3bcad
;
	.fopt		compiler,"cc65 v 2.19 - Git ce3bcad"
	.setcpu		"6502"
	.smart		on
	.autoimport	on
	.case		on
	.debuginfo	off
	.importzp	sp, sreg, regsave, regbank
	.importzp	tmp1, tmp2, tmp3, tmp4, ptr1, ptr2, ptr3, ptr4
	.macpack	longbranch

	.export		_main

; ---------------------------------------------------------------
; int __near__ main (void)
; ---------------------------------------------------------------

.segment	"CODE"

.proc	_main: near

.segment	"CODE"

	lda     #$00
	sta     $0050
L002B:	lda     $0050
	cmp     #$FF
	beq     L002C
	ldy     $0050
	ldx     #$00
	lda     $F000,y
	sta     M0002
	stx     M0002+1
	lda     #$20
	sta     $2006
	lda     $0050
	sta     $2006
	lda     M0002
	sta     $2007
	inc     $0050
	jmp     L002B
L002C:	lda     #$00
	sta     $0009
	lda     #$01
	sta     $0011
	sta     $0013
	lda     #$BF
	sta     $0050
L002D:	lda     $0050
	cmp     #$10
	beq     L002E
	ldy     $0050
	ldx     #$00
	lda     $FC00,y
	sta     M0002
	stx     M0002+1
	lda     #$3F
	sta     $2006
	lda     $0050
	sta     $2006
	lda     M0002
	sta     $2007
	inc     $0050
	jmp     L002D
L002E:	lda     #$20
	sta     $2006
	lda     #$01
	sta     $2006
	lda     #$00
	sta     $2007
	lda     #$18
	sta     $2001
L002F:	lda     #$01
	sta     $4016
	lda     #$00
	sta     $4016
	sta     M0001
L0030:	lda     M0001
	cmp     #$08
	beq     L0031
	lda     $4016
	and     #$01
	sta     $0014
	lda     $0015
	asl     a
	sta     $0015
	lda     $0014
	ora     $0015
	sta     $0015
	inc     M0001
	jmp     L0030
L0031:	lda     $0015
	cmp     #$80
	bne     L0032
	lda     $0016
	cmp     $0015
	jeq     L0038
	inc     $0008
	lda     $0015
	jmp     L002A
L0032:	lda     $0015
	cmp     #$40
	bne     L0033
	lda     $0016
	cmp     $0015
	beq     L0038
	lda     $0008
	sec
	sbc     #$01
	sta     $0008
	lda     $0015
	jmp     L002A
L0033:	lda     $0015
	cmp     #$01
	bne     L0034
	lda     $0016
	cmp     $0015
	beq     L0038
	inc     $0007
	lda     #$00
	sta     $0008
	lda     $0015
	jmp     L002A
L0034:	lda     $0015
	cmp     #$02
	bne     L0035
	lda     $0016
	cmp     $0015
	beq     L0038
	lda     $0007
	sec
	sbc     #$01
	sta     $0007
	lda     #$00
	sta     $0008
	lda     $0015
	jmp     L002A
L0035:	lda     $0015
	cmp     #$04
	bne     L0036
	lda     $0016
	cmp     $0015
	beq     L0038
	lda     $0007
	clc
	adc     #$20
	sta     $0007
	lda     #$00
	sta     $0008
	lda     $0015
	jmp     L002A
L0036:	lda     $0015
	cmp     #$08
	bne     L0037
	lda     $0016
	cmp     $0015
	beq     L0038
	lda     $0007
	sec
	sbc     #$20
	sta     $0007
	lda     #$00
	sta     $0008
	lda     $0015
	jmp     L002A
L0037:	lda     #$00
L002A:	sta     $0016
L0038:	lda     $0009
	cmp     $0008
	jeq     L002F
	lda     #$00
	sta     $2001
	lda     #$20
	sta     $2006
	lda     $0007
	sta     $2006
	lda     $0008
	sta     $2007
	lda     #$20
	sta     $2006
	lda     #$01
	sta     $2006
	lda     #$00
	sta     $2007
	lda     #$18
	sta     $2001
	lda     $0008
	sta     $0009
	jmp     L002F

.segment	"BSS"

M0001:
	.res	6,$00
M0002:
	.res	2,$00

.endproc

