;
; File generated by cc65 v 2.19 - Git ce3bcad
;
	.fopt		compiler,"cc65 v 2.19 - Git ce3bcad"
	.setcpu		"6502"
	.smart		on
	.autoimport	on
	.case		on
	.debuginfo	off
	.importzp	sp, sreg, regsave, regbank
	.importzp	tmp1, tmp2, tmp3, tmp4, ptr1, ptr2, ptr3, ptr4
	.macpack	longbranch
	.export		_MEM_POINTER
	.export		_draw

.segment	"BSS"

_MEM_POINTER:
	.res	1,$00

; ---------------------------------------------------------------
; void __near__ draw (void)
; ---------------------------------------------------------------

.segment	"CODE"

.proc	_draw: near

.segment	"CODE"

	lda     #$00
	sta     $0040
L0016:	lda     $0040
	cmp     #$FF
	bcs     L0017
	ldy     $0040
	lda     $EFF0,y
	sta     _MEM_POINTER
	lda     #$20
	sta     $2006
	lda     $0040
	sta     $2006
	lda     _MEM_POINTER
	sta     $2007
	inc     $0040
	jmp     L0016
L0017:	lda     #$00
	sta     $0040
L0018:	lda     $0040
	cmp     #$FF
	bcs     L0019
	ldy     $0040
	lda     $F0F0,y
	sta     _MEM_POINTER
	lda     #$21
	sta     $2006
	lda     $0040
	sta     $2006
	lda     _MEM_POINTER
	sta     $2007
	inc     $0040
	jmp     L0018
L0019:	lda     #$00
	sta     $0040
L001A:	lda     $0040
	cmp     #$FF
	bcs     L001B
	ldy     $0040
	lda     $F1F0,y
	sta     _MEM_POINTER
	lda     #$22
	sta     $2006
	lda     $0040
	sta     $2006
	lda     _MEM_POINTER
	sta     $2007
	inc     $0040
	jmp     L001A
L001B:	lda     #$00
	sta     $0040
L001C:	lda     $0040
	cmp     #$FF
	bcs     L0012
	ldy     $0040
	lda     $F2F0,y
	sta     _MEM_POINTER
	lda     #$23
	sta     $2006
	lda     $0040
	sta     $2006
	lda     _MEM_POINTER
	sta     $2007
	inc     $0040
	jmp     L001C
L0012:	rts

.endproc

