;
; File generated by cc65 v 2.19 - Git ce3bcad
;
	.fopt		compiler,"cc65 v 2.19 - Git ce3bcad"
	.setcpu		"6502"
	.smart		on
	.autoimport	on
	.case		on
	.debuginfo	off
	.importzp	sp, sreg, regsave, regbank
	.importzp	tmp1, tmp2, tmp3, tmp4, ptr1, ptr2, ptr3, ptr4
	.macpack	longbranch
	.export		_MEM_POINTER
	.export		_main
	.export		_draw
	.export		_get_controller_input

.segment	"BSS"

_MEM_POINTER:
	.res	1,$00

; ---------------------------------------------------------------
; void __near__ main (void)
; ---------------------------------------------------------------

.segment	"CODE"

.proc	_main: near

.segment	"CODE"

	jsr     _draw
	lda     #$BF
	sta     $0040
L000A:	lda     $0040
	cmp     #$20
	beq     L000C
	ldy     $0040
	lda     $FC00,y
	sta     _MEM_POINTER
	lda     #$3F
	sta     $2006
	lda     $0040
	sta     $2006
	lda     _MEM_POINTER
	sta     $2007
	inc     $0040
	jmp     L000A
L000C:	sta     $2006
	lda     #$00
	sta     $2006
	sta     $2007
	lda     #$1E
	sta     $2001
L0007:	jsr     _get_controller_input
	jmp     L0007

.endproc

; ---------------------------------------------------------------
; void __near__ draw (void)
; ---------------------------------------------------------------

.segment	"CODE"

.proc	_draw: near

.segment	"CODE"

	lda     #$00
	sta     $0040
L0016:	lda     $0040
	cmp     #$FF
	bcs     L0017
	ldy     $0040
	lda     $EFF0,y
	sta     _MEM_POINTER
	lda     #$20
	sta     $2006
	lda     $0040
	sta     $2006
	lda     _MEM_POINTER
	sta     $2007
	inc     $0040
	jmp     L0016
L0017:	lda     #$00
	sta     $0040
L0018:	lda     $0040
	cmp     #$FF
	bcs     L0019
	ldy     $0040
	lda     $F0F0,y
	sta     _MEM_POINTER
	lda     #$21
	sta     $2006
	lda     $0040
	sta     $2006
	lda     _MEM_POINTER
	sta     $2007
	inc     $0040
	jmp     L0018
L0019:	lda     #$00
	sta     $0040
L001A:	lda     $0040
	cmp     #$FF
	bcs     L001B
	ldy     $0040
	lda     $F1F0,y
	sta     _MEM_POINTER
	lda     #$22
	sta     $2006
	lda     $0040
	sta     $2006
	lda     _MEM_POINTER
	sta     $2007
	inc     $0040
	jmp     L001A
L001B:	lda     #$00
	sta     $0040
L001C:	lda     $0040
	cmp     #$FF
	bcs     L0012
	ldy     $0040
	lda     $F2F0,y
	sta     _MEM_POINTER
	lda     #$23
	sta     $2006
	lda     $0040
	sta     $2006
	lda     _MEM_POINTER
	sta     $2007
	inc     $0040
	jmp     L001C
L0012:	rts

.endproc

; ---------------------------------------------------------------
; void __near__ get_controller_input (void)
; ---------------------------------------------------------------

.segment	"CODE"

.proc	_get_controller_input: near

.segment	"CODE"

	lda     #$01
	sta     $4016
	lda     #$00
	sta     $4016
	sta     $0000
L0006:	lda     $0000
	cmp     #$08
	beq     L0003
	lda     $4016
	and     #$01
	sta     $0030
	lda     $0031
	asl     a
	sta     $0031
	lda     $0030
	ora     $0031
	sta     $0031
	inc     $0000
	jmp     L0006
L0003:	rts

.endproc

